### ISSUE TITLE
Why does this repository exist

### ISSUE THREAD

**Issue by Kontorted** [MCLabyMod/LabyMod-1.8#2]
I don't see the reason to upload obfuscated code. It provides us with nothing useful.

**Comment by Bluscream** [comment]
It helped other people so far, noone forces you to stay here.

**Comment by Kontorted** [comment]
@BlueScream, how did it help anyone? Not only is the code completely obfuscated (seems like it was pulled out of the .jar rather than decompiled), but it provides no relevant content to LabyMod. The only reason this repository is useful is for its "releases", which serve to download the legacy version. You could at *least* decompile with fernflower.
